include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

# stages defines the dependencies between the different stages of the pipeline
stages:
  - lint
  - build
  - generate
  - test
  - deploy


black:
  stage: lint
  image: pyfound/black:23.11.0
  before_script:
    - cd ./api
    - black --version
  script:
    - black . --check

pylint:
  stage: lint
  image: python:3.9
  before_script:
    - pip install .
  script:
    - pylint api



build-on-push:
  stage: build
  extends: .build-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/kg-inference-api-build
    KANIKO_EXTRA_ARGS: --build-arg GITLAB_TOKEN=$CI_JOB_TOKEN --build-arg GITLAB_USERNAME='gitlab-ci-token'
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi


build-and-deploy-api-image-in-registry:
  stage: deploy
  extends: .build-image-using-kaniko
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
      variables:
        CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/kg-inference-api-dev
        CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
        REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    - if: $CI_COMMIT_TAG
      when: on_success
      variables:
        CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/kg-inference-api-production
        CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
        REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
  variables:
    KANIKO_EXTRA_ARGS: --build-arg GITLAB_TOKEN=$CI_JOB_TOKEN --build-arg GITLAB_USERNAME='gitlab-ci-token'
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi


build-and-deploy-api-image-in-dockerhub:
  stage: deploy
  extends: .build-image-using-kaniko
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
  variables:
    CI_PROJECT_DIR: /builds/dke/apps/kg-inference-api
    CI_REGISTRY_IMAGE: bluebrain/kg-inference-api
    CI_REGISTRY: https://index.docker.io/v1/
    CI_REGISTRY_USER: bbpbuildbot
    CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD_DOCKERHUB
    REGISTRY_IMAGE_TAG: latest
    KANIKO_EXTRA_ARGS: --build-arg GITLAB_TOKEN=$CI_JOB_TOKEN --build-arg GITLAB_USERNAME='gitlab-ci-token'
    KUBERNETES_MEMORY_LIMIT: 4Gi
    KUBERNETES_MEMORY_REQUEST: 4Gi
