# docker-compose.yml


services:
  kg-inference-api:
    container_name: kg-inference-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BBP_NEXUS_ENDPOINT: https://bbp.epfl.ch/nexus/v1
      ENVIRONMENT: LOCAL
      RULES_BUCKET: bbp/inference-rules
      DATAMODELS_BUCKET: neurosciencegraph/datamodels
      WHITELISTED_CORS_URLS: https://bluebrainatlas.kcpdev.bbp.epfl.ch,https://bluebrainatlas.kcp.bbp.epfl.ch,https://kg-inference-frontend.kcp.bbp.epfl.ch,http://localhost:3000,https://bbp.epfl.ch
      ES_RULE_VIEW: https://bbp.epfl.ch/neurosciencegraph/data/views/aggreg-es/rule_view
      SPARQL_RULE_VIEW: https://bbp.epfl.ch/neurosciencegraph/data/views/aggreg-sp/rule_view
