# docker-compose.yml

version: '3.8'

services:
  api:
    build:
      context: .
      args:
        GITLAB_USERNAME: <MY_GITLAB_USERNAME>
        GITLAB_TOKEN: <MY_GITLAB_TOKEN>
    ports:
      - 8080:8080
    environment:
      BBP_NEXUS_ENDPOINT: https://bbp.epfl.ch/nexus/v1
      ENVIRONMENT: LOCAL
      RULES_BUCKET: bbp/inference-rules
      WHITELISTED_CORS_URLS: http://api:8000
    networks:
      - bluebrainatlas_default
networks:
  bluebrainatlas_default:
    external: true