# docker-compose.yml

version: "3.8"

services:
  kg-inference-api:
    container_name: kg-inference-api
    build:
      dockerfile: ./api/Dockerfile
      args:
        GITLAB_USERNAME: <MY_GITLAB_USERNAME>
        GITLAB_TOKEN: <MY_GITLAB_TOKEN>
    ports:
      - "8080:8080"
    environment:
      NEXUS_TOKEN: "TODO"
      BBP_NEXUS_ENDPOINT: "https://bbp.epfl.ch/nexus/v1"
      DATAMODELS_BUCKET: "neurosciencegraph/datamodels"
      ENVIRONMENT: "LOCAL"
      ES_RULE_VIEW: "https://bbp.epfl.ch/neurosciencegraph/data/views/aggreg-es/rule_view_no_tag"
      RULES_BUCKET: "bbp/inference-rules"
      SPARQL_RULE_VIEW: "https://bbp.epfl.ch/neurosciencegraph/data/views/aggreg-sp/rule_view_no_tag"
      WHITELISTED_CORS_URLS: "http://localhost:3050,https://bluebrainatlas-refactoring.kcpdev.bbp.epfl.ch,https://bbp.epfl.ch/atlas"
