# docker-compose.yml

version: '3.8'

services:
  api:
    build:
      context: ./api
      args:
        GITLAB_USERNAME: <MY_GITLAB_USERNAME>
        GITLAB_TOKEN: <MY_GITLAB_TOKEN>
    ports:
      - "8080:8080"
    environment:
      BBP_NEXUS_ENDPOINT: https://bbp.epfl.ch/nexus/v1
      ENVIRONMENT: LOCAL
      RULES_BUCKET: bbp/inference-rules
      DATAMODELS_BUCKET: neurosciencegraph/datamodels
      WHITELISTED_CORS_URLS: http://api:8000
      NEXUS_TOKEN: "TODO"
  front:
    build:
      context: ./frontend
    ports:
      - "8050:8050"
    environment:
      ENVIRONMENT: LOCAL
    depends_on:
      - api

