Model:
  name: RdfModel
  origin: store
  source: BlueBrainNexus
  context:
    iri: "https://bbp.neuroshapes.org"
    bucket: "neurosciencegraph/datamodels"

Store:
  model:
    name: RdfModel
  name: BlueBrainNexus
  endpoint: https://bbp.epfl.ch/nexus/v1
  searchendpoints:
    sparql:
      endpoint: "https://bbp.epfl.ch/neurosciencegraph/data/views/aggreg-sp/dataset"
    elastic:
      endpoint: "https://bbp.epfl.ch/neurosciencegraph/data/420e53b8-db21-4f70-a534-d799c4b59b5d"
      mapping: "https://bbp.epfl.ch/neurosciencegraph/data/views/es/dataset"
      default_str_keyword_field: "keyword"
  vocabulary:
    metadata:
      iri: "https://bluebrain.github.io/nexus/contexts/metadata.json"
      local_iri: "https://bluebrainnexus.io/contexts/metadata.json"
    namespace: "https://bluebrain.github.io/nexus/vocabulary/"
    deprecated_property: "https://bluebrain.github.io/nexus/vocabulary/deprecated"
    project_property: "https://bluebrain.github.io/nexus/vocabulary/project"
  max_connection: 5
  versioned_id_template: "{x.id}?rev={x._store_metadata._rev}"
  file_resource_mapping: config/forge_configs/mappings/file-to-resource-mapping.hjson


Formatters:
  identifier: https://bbp.epfl.ch/neurosciencegraph/data/{}/{}
  identifier_with_org_project: https://bbp.epfl.ch/data/{}/{}/{}
